import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, ShieldCheck, Wallet, Zap } from 'lucide-react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Logo from '../components/Logo';

export default function Auth({ mode }){
 const isLogin=mode==='login'; const [form,setForm]=useState({name:'',email:'',password:''}); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const {login,register}=useAuth(); const nav=useNavigate();
 const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{if(isLogin) await login({email:form.email,password:form.password});else await register(form);nav('/')}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <div className="auth-page"><section className="auth-visual"><div className="visual-inner"><Logo/><div className="visual-copy"><span className="pill"><Zap size={14}/> Personal finance, simplified</span><h1>Know where your money <em>really</em> goes.</h1><p>Track income, control spending and make better financial decisions from one calm, beautiful dashboard.</p><div className="visual-cards"><div><strong>Rs. 84,500</strong><span>Current balance</span><b>+12.8%</b></div><div><span>This month</span><strong>Rs. 28,420</strong><div className="fake-bars"><i/><i/><i/><i/><i/><i/><i/></div></div></div></div><div className="trust"><ShieldCheck size={17}/> Your data stays private to your account</div></div></section><section className="auth-form-wrap"><div className="auth-form"><div className="mobile-auth-logo"><Logo/></div><p className="eyebrow">{isLogin?'WELCOME BACK':'GET STARTED'}</p><h2>{isLogin?'Welcome back':'Create your account'}</h2><p className="auth-sub">{isLogin?'Sign in to continue managing your finances.':'Start tracking your money in a few seconds.'}</p>{error&&<div className="error-box">{error}</div>}<form onSubmit={submit}>{!isLogin&&<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Khalid Kamal"/></label>}<label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<div className="password-field"><input required minLength="6" type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button className="auth-submit" disabled={busy}>{busy?'Please wait...':isLogin?'Sign in':'Create account'}<ArrowRight size={18}/></button></form><p className="auth-switch">{isLogin?"Don't have an account?":"Already have an account?"} <Link to={isLogin?'/register':'/login'}>{isLogin?'Create one':'Sign in'}</Link></p><div className="auth-features"><span><Wallet size={16}/> Track everything</span><span>•</span><span>Private & secure</span></div></div></section></div>
}
