import { useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CreditCard, Plus, Wallet, TrendingUp } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../services/api';
import { money, dateLabel } from '../utils/format';
import { useNavigate } from 'react-router-dom';
import TransactionModal from '../components/TransactionModal';
import Toast from '../components/Toast';

const chartMonthName = (m,y)=>new Date(y,m-1,1).toLocaleString('en-US',{month:'short'});
export default function Dashboard(){
 const [summary,setSummary]=useState({income:0,expense:0,balance:0,byCategory:[],monthly:[]}); const [recent,setRecent]=useState([]); const [modal,setModal]=useState(false); const [toast,setToast]=useState(''); const [loading,setLoading]=useState(true); const navigate=useNavigate();
 const load=async()=>{setLoading(true);try{const [s,t]=await Promise.all([api.summary(),api.transactions({})]);setSummary(s);setRecent(t.transactions.slice(0,6))}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const chart=useMemo(()=>{const map={};summary.monthly.forEach(x=>{const k=`${x._id.year}-${x._id.month}`;map[k]??={name:chartMonthName(x._id.month,x._id.year),income:0,expense:0};map[k][x._id.type]=x.total});return Object.values(map).slice(-6)},[summary.monthly]);
 const save=async body=>{await api.createTransaction(body);await load();setToast('Transaction added successfully')};
 return <><div className="page-head"><div><p className="eyebrow">OVERVIEW</p><h1>Financial dashboard</h1><p className="muted">A clear picture of your money, all in one place.</p></div><button className="btn primary" onClick={()=>setModal(true)}><Plus size={18}/> Add transaction</button></div><div className="stat-grid"><Stat icon={Wallet} label="Total balance" value={money(summary.balance)} tone="purple" hint="Income minus expenses"/><Stat icon={ArrowDownLeft} label="Total income" value={money(summary.income)} tone="green" hint="All recorded income"/><Stat icon={ArrowUpRight} label="Total expenses" value={money(summary.expense)} tone="red" hint="All recorded spending"/><Stat icon={CreditCard} label="Transactions" value={summary.transactionCount||0} tone="blue" hint="Across your account"/></div><div className="dashboard-grid"><section className="card chart-card"><div className="card-head"><div><h3>Income vs expenses</h3><p>Monthly movement</p></div><span className="chart-badge"><TrendingUp size={15}/> Last 6 months</span></div>{chart.length?<ResponsiveContainer width="100%" height={280}><BarChart data={chart} barGap={8}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="income" name="Income" radius={[5,5,0,0]} fill="#6d5dfc"/><Bar dataKey="expense" name="Expense" radius={[5,5,0,0]} fill="#f06a6a"/></BarChart></ResponsiveContainer>:<EmptyChart/>}</section><section className="card category-card"><div className="card-head"><div><h3>Top spending</h3><p>By expense category</p></div></div>{summary.byCategory.length?<div className="category-list">{summary.byCategory.slice(0,5).map((x,i)=><div className="category-row" key={x._id}><div className="cat-dot" style={{'--i':i}}/><div className="cat-info"><strong>{x._id}</strong><span>{money(x.total)}</span></div><div className="progress"><i style={{width:`${Math.max(8,x.total/summary.expense*100)}%`}}/></div></div>)}</div>:<EmptyChart text="Add an expense to see categories."/>}</section></div><section className="card recent-card"><div className="card-head"><div><h3>Recent transactions</h3><p>Your latest activity</p></div><button className="text-btn" onClick={()=>navigate('/transactions')}>View all →</button></div>{loading?<div className="loading-row">Loading transactions...</div>:recent.length?<div className="transaction-list">{recent.map(t=><TransactionRow key={t._id} t={t}/>)}</div>:<EmptyChart text="No transactions yet. Add your first one."/>}</section><TransactionModal open={modal} onClose={()=>setModal(false)} onSave={save}/><Toast message={toast} onClose={()=>setToast('')}/></>
}
function Stat({icon:Icon,label,value,hint,tone}){return <div className="stat card"><div className={`stat-icon ${tone}`}><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div>}
export function TransactionRow({t,actions}){return <div className="transaction-row"><div className={`transaction-icon ${t.type}`} >{t.type==='income'?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</div><div className="transaction-main"><strong>{t.title}</strong><span>{t.category} · {dateLabel(t.date)}</span></div><strong className={t.type==='income'?'amount income':'amount expense'}>{t.type==='income'?'+':'-'} {money(t.amount)}</strong>{actions}</div>}
function EmptyChart({text='No data yet. Add transactions to populate this chart.'}){return <div className="empty-chart"><CalendarDays size={30}/><span>{text}</span></div>}
