import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Download, FileText } from 'lucide-react';
import { api } from '../services/api';
import { money } from '../utils/format';

export default function Reports(){
 const [data,setData]=useState(null); useEffect(()=>{api.summary().then(setData)},[]);
 const pie=useMemo(()=>data?.byCategory?.map(x=>({name:x._id,value:x.total}))||[],[data]);
 const monthly=useMemo(()=>{const map={};(data?.monthly||[]).forEach(x=>{const key=`${x._id.year}-${x._id.month}`;map[key]??={name:new Date(x._id.year,x._id.month-1).toLocaleString('en-US',{month:'short'}),income:0,expense:0};map[key][x._id.type]=x.total});return Object.values(map).slice(-12)},[data]);
 const exportCsv=()=>{if(!data)return;const rows=[['Category','Amount'],...pie.map(x=>[x.name,x.value])];const csv=rows.map(r=>r.join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='expense-report.csv';a.click();URL.revokeObjectURL(a.href)};
 if(!data)return <div className="loading-screen">Building your report...</div>;
 return <><div className="page-head"><div><p className="eyebrow">INSIGHTS</p><h1>Financial reports</h1><p className="muted">Understand your spending patterns and cash flow.</p></div><button className="btn secondary" onClick={exportCsv}><Download size={17}/> Export CSV</button></div><div className="report-highlight"><div><span>Net balance</span><strong>{money(data.balance)}</strong></div><div><span>Income</span><strong className="positive">{money(data.income)}</strong></div><div><span>Expenses</span><strong className="negative">{money(data.expense)}</strong></div><div><span>Savings rate</span><strong>{data.income?`${Math.max(0,Math.round(data.balance/data.income*100))}%`:'0%'}</strong></div></div><div className="dashboard-grid reports-grid"><section className="card chart-card"><div className="card-head"><div><h3>Cash flow</h3><p>Income and expenses by month</p></div></div>{monthly.length?<ResponsiveContainer width="100%" height={340}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)}/><Legend/><Bar dataKey="income" name="Income" fill="#6d5dfc" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Expense" fill="#f06a6a" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<div className="empty-chart"><FileText size={28}/><span>No monthly data yet.</span></div>}</section><section className="card chart-card"><div className="card-head"><div><h3>Expense breakdown</h3><p>Where your money goes</p></div></div>{pie.length?<ResponsiveContainer width="100%" height={340}><PieChart><Pie data={pie} dataKey="value" nameKey="name" cx="50%" cy="48%" innerRadius={75} outerRadius={115} paddingAngle={3}>{pie.map((_,i)=><Cell key={i} fill={['#6d5dfc','#36b37e','#f5a524','#f06a6a','#3b82f6','#8b5cf6','#14b8a6'][i%7]}/>)}</Pie><Tooltip formatter={v=>money(v)}/><Legend/></PieChart></ResponsiveContainer>:<div className="empty-chart"><FileText size={28}/><span>No expenses recorded.</span></div>}</section></div><section className="card report-table"><div className="card-head"><div><h3>Category summary</h3><p>Total spending by category</p></div></div>{pie.length?pie.map(x=><div className="report-line" key={x.name}><span>{x.name}</span><strong>{money(x.value)}</strong><span className="share">{data.expense?Math.round(x.value/data.expense*100):0}%</span></div>):<div className="empty-state"><h3>No category data</h3></div>}</section></>
}
