import { useEffect, useMemo, useState } from 'react';
import { Edit3, Plus, Search, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import TransactionModal from '../components/TransactionModal';
import Toast from '../components/Toast';
import { api } from '../services/api';
import { money, dateLabel } from '../utils/format';
import { TransactionRow } from './Dashboard';

export default function Transactions(){
 const [items,setItems]=useState([]); const [filters,setFilters]=useState({search:'',type:'all',category:'all'}); const [modal,setModal]=useState(false); const [editing,setEditing]=useState(null); const [toast,setToast]=useState(''); const [loading,setLoading]=useState(true); const [params,setParams]=useSearchParams();
 const load=async()=>{setLoading(true);try{const q={};if(filters.type!=='all')q.type=filters.type;if(filters.category!=='all')q.category=filters.category;if(filters.search)q.search=filters.search;const r=await api.transactions(q);setItems(r.transactions)}finally{setLoading(false)}};
 useEffect(()=>{load()},[filters.type,filters.category,filters.search]); useEffect(()=>{if(params.get('add')){setModal(true);params.delete('add');setParams(params,{replace:true})}},[]);
 const save=async body=>{if(editing){await api.updateTransaction(editing._id,body);setToast('Transaction updated')}else{await api.createTransaction(body);setToast('Transaction added')}setEditing(null);await load()};
 const remove=async id=>{if(!window.confirm('Delete this transaction? This cannot be undone.'))return;await api.deleteTransaction(id);setToast('Transaction deleted');load()};
 const total=useMemo(()=>items.reduce((a,x)=>a+(x.type==='income'?x.amount:-x.amount),0),[items]);
 return <><div className="page-head"><div><p className="eyebrow">ACTIVITY</p><h1>Transactions</h1><p className="muted">Manage every income and expense in your account.</p></div><button className="btn primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={18}/> Add transaction</button></div><section className="card filters"><div className="search"><Search size={18}/><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Search transactions..."/>{filters.search&&<button onClick={()=>setFilters({...filters,search:''})}><X size={15}/></button>}</div><div className="filter-select"><SlidersHorizontal size={17}/><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="all">All types</option><option value="income">Income</option><option value="expense">Expense</option></select></div><div className="filter-select"><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="all">All categories</option>{['Food','Transport','Shopping','Bills','Entertainment','Health','Education','Salary','Freelance','Business','Investment','Other'].map(x=><option key={x}>{x}</option>)}</select></div></section><section className="card table-card"><div className="table-summary"><span>{loading?'Loading...':`${items.length} transaction${items.length!==1?'s':''}`}</span><strong>Filtered balance: <b className={total>=0?'positive':'negative'}>{money(total)}</b></strong></div>{!loading&&items.length===0?<div className="empty-state"><div className="empty-icon"><Search/></div><h3>No transactions found</h3><p>Try another search or add a new transaction.</p><button className="btn primary" onClick={()=>setModal(true)}><Plus size={17}/> Add transaction</button></div>:<div className="transaction-list full-list">{items.map(t=><TransactionRow key={t._id} t={t} actions={<div className="row-actions"><button onClick={()=>{setEditing(t);setModal(true)}} title="Edit"><Edit3 size={16}/></button><button onClick={()=>remove(t._id)} title="Delete"><Trash2 size={16}/></button></div>}/>)}</div>}</section><TransactionModal open={modal} onClose={()=>{setModal(false);setEditing(null)}} onSave={save} transaction={editing}/><Toast message={toast} onClose={()=>setToast('')}/></>
}
